### ISSUE TITLE
Will this project be deprecated?

### ISSUE THREAD

**Issue by scresante** [plasticuproject/nvd_api#15]
With the NVD having its own API now and the announcement that the NVD plans to retire all legacy data feeds in September 2023, does that mean this project will be deprecated at that time?

**Comment by plasticuproject** [comment]
Most likely yes, if they discontinue the data feeds. I'll archive it. I built this right before/around the time they launched their api lol.

**Comment by scresante** [comment]
Perhaps embed the .json.gz archives into the project here so they can live on here for posterity.
